apiVersion: networking,k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labales:
    name: myingress
spec:
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backed:
          service:
            name: <Service>
            port:
              number: <Port>
